### ISSUE TITLE
wot trajectory :Empty population list

### ISSUE THREAD

**Issue by annrosebright** [broadinstitute/wot#25]
Hi, I am trying to run wot on the simulated data provided with the tutorial. But i keep getting this error. Can you please help on why this error is occurring. I wanted to first run the commands on this dataset and apply it on our dataset. 

wot trajectory --tmap tmaps --cell_set cell_sets.gmt --time 10 --out traj.txt
Traceback (most recent call last):
  File "/home/brightann/.local/bin/wot", line 11, in <module>
    sys.exit(main())
  File "/home/brightann/.local/lib/python3.7/site-packages/wot/__main__.py", line 23, in main
    cmd.main(command_args)
  File "/home/brightann/.local/lib/python3.7/site-packages/wot/commands/trajectory.py", line 23, in main
    trajectory_ds = tmap_model.compute_trajectories(populations)
  File "/home/brightann/.local/lib/python3.7/site-packages/wot/tmap/transport_map_model.py", line 71, in compute_trajectories
    while self.can_pull_back(*populations):
  File "/home/brightann/.local/lib/python3.7/site-packages/wot/tmap/transport_map_model.py", line 187, in can_pull_back
    return self.timepoints.index(wot.tmap.unique_timepoint(*populations)) > 0
  File "/home/brightann/.local/lib/python3.7/site-packages/wot/tmap/util.py", line 24, in unique_timepoint
    raise ValueError("Empty population list")
ValueError: Empty population list

**Comment by annrosebright** [comment]
> Hi, I am trying to run wot on the simulated data provided with the tutorial. But i keep getting this error. Can you please help on why this error is occurring. I wanted to first run the commands on this dataset and apply it on our dataset.
> 
> wot trajectory --tmap tmaps --cell_set cell_sets.gmt --time 10 --out traj.txt
> Traceback (most recent call last):
> File "/home/brightann/.local/bin/wot", line 11, in 
> sys.exit(main())
> File "/home/brightann/.local/lib/python3.7/site-packages/wot/**main**.py", line 23, in main
> cmd.main(command_args)
> File "/home/brightann/.local/lib/python3.7/site-packages/wot/commands/trajectory.py", line 23, in main
> trajectory_ds = tmap_model.compute_trajectories(populations)
> File "/home/brightann/.local/lib/python3.7/site-packages/wot/tmap/transport_map_model.py", line 71, in compute_trajectories
> while self.can_pull_back(*populations):
> File "/home/brightann/.local/lib/python3.7/site-packages/wot/tmap/transport_map_model.py", line 187, in can_pull_back
> return self.timepoints.index(wot.tmap.unique_timepoint(*populations)) > 0
> File "/home/brightann/.local/lib/python3.7/site-packages/wot/tmap/util.py", line 24, in unique_timepoint
> raise ValueError("Empty population list")
> ValueError: Empty population list

Resolved by changing time point

**Comment by annrosebright** [comment]
Resolved by changing time point
