### ISSUE TITLE
wot trajectory_trends: tuple index out of range

### ISSUE THREAD

**Issue by annrosebright** [broadinstitute/wot#27]
wot trajectory_trends --trajectory traj.txt --matrix matrix.txt --out trends --cell_days days.txt 

/home/brightann/.local/lib/python3.7/site-packages/wot/io/io.py:786: FutureWarning: read_table is deprecated, use read_csv instead.

  engine='python', sep=None, dtype={'day': np.float64})

Traceback (most recent call last):

  File "/home/brightann/.local/bin/wot", line 11, in <module>

    sys.exit(main())

  File "/home/brightann/.local/lib/python3.7/site-packages/wot/__main__.py", line 23, in main

    cmd.main(command_args)

  File "/home/brightann/.local/lib/python3.7/site-packages/wot/commands/trajectory_trends.py", line 26, in main

    results = wot.tmap.compute_trajectory_trends_from_trajectory(trajectory_ds, matrix)

  File "/home/brightann/.local/lib/python3.7/site-packages/wot/tmap/transport_map_util.py", line 78, in compute_trajectory_trends_from_trajectory

    for j in range(trajectory_ds.X.shape[1]):

IndexError: tuple index out of range

**Comment by YubinXie** [comment]
same error here.

**Comment by joshua-gould** [comment]
Fixed in latest release

**Comment by geoffschieb** [comment]
Dear annrosebright,

We have just released WOT 1.0 along with a tutorial here:
https://broadinstitute.github.io/wot/tutorial/

I'm sending this to anyone who has expressed interest recently. Sorry if
you've received this multiple times.

Best,
Geoff
