### ISSUE TITLE
Trajectory tool works fine but trajectory trend fails 

### ISSUE THREAD

**Issue by rosshandler** [broadinstitute/wot#39]
Hi WOT team,

 Thanks for this awesome tool. I am finding a problem when computing the trajectory trends after running the trajectory tool with no issues (at least the output looks normal). 

The entire pipeline used to work fine. Then a friend help me with some other python package and I guess he changes something in pandas and now the trajectory trend command is crashing. I have reinstalled everything as well as updated wot but the error is still there. In summary the same input that used to work is not doing it anymore. Do you recognise this error:

wot trajectory_trends --trajectory traj.txt \
--matrix matrix.mtx \
--out trends --cell_days time.txt

Traceback (most recent call last):
  File "/homes/iimaz/.local/bin/wot", line 11, in <module>
    sys.exit(main())
  File "/homes/iimaz/.local/lib/python3.6/site-packages/wot/__main__.py", line 23, in main
    cmd.main(command_args)
  File "/homes/iimaz/.local/lib/python3.6/site-packages/wot/commands/trajectory_trends.py", line 24, in main
    matrix = wot.io.read_dataset(args.matrix)
  File "/homes/iimaz/.local/lib/python3.6/site-packages/wot/io/io.py", line 472, in read_dataset
    header=None)
  File "/homes/iimaz/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 702, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/homes/iimaz/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 429, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/homes/iimaz/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 895, in __init__
    self._make_engine(self.engine)
  File "/homes/iimaz/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1122, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/homes/iimaz/miniconda3/lib/python3.6/site-packages/pandas/io/parsers.py", line 1853, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 545, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

Best,
Ivan

**Comment by rosshandler** [comment]
Brief update: I discovered this does not crash if I use a non sparse matrix. It worked fine with a normal matrix. 

Best,
Ivan
