### ISSUE TITLE
updating to version 0.5.6 breaks all commands

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#50]
The update was successful, but unfortunately all the scripts and command afterwards breaks with errors. first i have tried to run the example scripts you provided with the github repository, which all don't work any more (issue #49). 

Now I have tried to run calculate the transport maps, but it also breaks with an error.

```
$ wot optimal_transport --matrix p2_matrix.transposed.txt --cell_days p2_timepoint.txt  --out tmaps_p2_timepoint --format loom --local_pca 30

Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/envs/Waddington/bin/wot", line 11, in <module>
    load_entry_point('wot', 'console_scripts', 'wot')()  
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/wot/__main__.py", line 23, in main
    cmd.main(command_args)
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/wot/commands/optimal_transport.py", line 23, in main
    ot_model = wot.commands.initialize_ot_model_from_args(args)
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/wot/commands/util.py", line 47, in initialize_ot_model_from_args
    covariate=args.covariate if hasattr(args, 'covariate') else None
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/wot/ot/initializer.py", line 39, in initialize_ot_model
    return OTModel(ds, **kwargs)
  File "/home/yeroslaviz/miniconda3/envs/Waddington/lib/python3.7/site-packages/wot/wot/ot/ot_model.py", line 111, in __init__
    raise ValueError("Days information not available for matrix")
ValueError: Days information not available for matrix
```

I have all the file in the same directory with the correct format

```
$ tree -L 1 ./
./
├── p11_ca140_geneset.gmt
├── p2_ca143_geneset.gmt
├── p2_gene_set.AllTP.gmt
├── p2_gene_set.gmt
├── p2_matrix.transposed.txt
├── p2_timepoint.txt
```

```
$ head p2_timepoint.txt 
id      day
p2_cortex_143_AAACCTGAGGCTAGGT  2
p2_cortex_143_AAACGGGCAATCGGTT  2
p2_cortex_143_AAAGTAGCATAAAGGT  2
...
```
gene expression matrix
```
id      Xkr4    Mrpl15  Lypla1 ...
p2_cortex_143_AAACCTGAGGCTAGGT  -0.219520647107675      -0.729889404055677 ...
...
```

any ideas?

**Comment by geoffschieb** [comment]
Hi,

We are in the process of replacing the Examples page with a tutorial based
on the real data from the reprogramming dataset.

This will be available next week.

Best,
Geoff

PS: Actually, the notebooks are in Git if you look carefully :-)
But we are still fleshing parts out and will release the first draft of
those next week.

**Comment by frymor** [comment]
I have seen the notebooks in the master branch, but hadn't look into them, as I wasn't aware about the updates. It will be great to have the newer version to run my project. I will be happy to test it for you :-)

It would be great if you can let me know, when the new version is online and ready.
thanks
