### ISSUE TITLE
optimal_transport_validation error 

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#57]
Calculating the validation throws back an error:

```
$ wot optimal_transport_validation --matrix matrix.txt --cell_days days.txt --covariate covariate.txt

local_pca set to 30, above gene count of 7. Disabling PCA
Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2657, in get_loc
    return self._engine.get_loc(key)
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'full'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/bin/wot", line 11, in <module>
    load_entry_point('wot', 'console_scripts', 'wot')()
  File "/home/yeroslaviz/projects/AnnB/TestingEnv/wot1.0.0/wot/wot/__main__.py", line 21, in main
    cmd.main(command_args)
  File "/home/yeroslaviz/projects/AnnB/TestingEnv/wot1.0.0/wot/wot/commands/optimal_transport_validation.py", line 73, in main
    summary_stats = summary[summary['full'] == False]
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/pandas/core/frame.py", line 2927, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2659, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1601, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1608, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'full'
```

**Comment by frymor** [comment]
Hi,
 I was wondering if there is any intentions of trying to fix the problems in the new version, or if you need more information to do so
thanks, Assa

**Comment by joshua-gould** [comment]
I'm unable to reproduce the error with wot 1.0.2
