### ISSUE TITLE
error calculating gene_set scores "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by frymor** [broadinstitute/wot#61]
When trying to calculate the gene scores with the new version (1.0.2), I  encounter a few problems.

An error creating the gene-set scores appears when trying to get a `gct` file format.

when running the command  
```
wot gene_set_scores --matrix oldData/matrix.txt --gene_sets oldData/gene_sets.gmt --out  gene_set --format gct --method mean_z_score
```
I get the following error:
```
Traceback (most recent call last):
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/bin/wot", line 10, in <module>
    sys.exit(main())
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/wot/__main__.py", line 21, in main
    cmd.main(command_args)
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/wot/commands/gene_set_scores.py", line 100, in main
    path=name, output_format=args.format)
  File "/home/yeroslaviz/miniconda3/envs/wot1.0/lib/python3.7/site-packages/wot/io/io.py", line 660, in write_dataset
    '\t' + str(len(ds.var.columns)) + '\n')
```

Another request would be to maybe create all the gene sets in just one file. This would make runnging the cell-set calculation much easier and streamlined. 

thanks Assa

**Comment by joshua-gould** [comment]
Fixed writing gct error
