### ISSUE TITLE
wot: error: argument command: invalid choice: 'neighborhood_graph'

### ISSUE THREAD

**Issue by mbk0asis** [broadinstitute/wot#71]
Hi!

I was going to test run 'wot' with the example data in the homepage, but I got stuck in the beginning. 

I copied the command and pasted to run the following command
`wot neighborhood_graph --matrix data/ExprMatrix.var.genes.h5ad --space dmap --neighbors 50 --pca_comps 100 --diff_comps 20 --out fle-input`
and obtained a following error 
`wot: error: argument command: invalid choice: 'neighborhood_graph' (choose from 'convert_matrix', 'cells_by_gene_set', 'census', 'diff_exp', 'fates', 'gene_set_scores', 'optimal_transport', 'optimal_transport_validation', 'trajectory', 'trajectory_divergence', 'trajectory_trends', 'transition_table')`

I saw 'neighborhood_graph' command in the homepage, but the error said like no such tool existed.
What could be the problem here?

Thank you!

**Comment by joshua-gould** [comment]
Sorry that part of our documentation is out of date. I've removed the command from the documentation. We now recommend using [Pegasus](https://pegasus.readthedocs.io/en/latest/) to generate embeddings.

**Comment by mbk0asis** [comment]
Thank you for reply!

Is threre any tutorials I can follow for Pegasus?



2019년 10월 18일 (금) 오후 8:22, Joshua Gould <notifications@github.com>님이 작성:

**Comment by joshua-gould** [comment]
Documentation is available at
https://pegasus.readthedocs.io/en/latest/index.html

**Comment by mbk0asis** [comment]
I'm sorry to bother you, but would you explain exactly which step I should use Pegasus?

And I'm getting another error when running 'wot trajectory_trends'. 
Was this command also deprecated?
The command and the error message are as follow;

```

$ wot trajectory_trends --trajectory wot_trajectory.txt --cell_days data/cell_days.txt --matrix data/ExprMatrix.h5ad --gene_filter Nanog,Obox6,Zfp42 --plot
/usr/local/lib/python3.6/dist-packages/pegasus/__init__.py:6: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'TkAgg' by the following code:
  File "/usr/local/bin/wot", line 7, in <module>
    from wot.__main__ import main
  File "/usr/local/lib/python3.6/dist-packages/wot/__init__.py", line 4, in <module>
    import wot.graphics
  File "/usr/local/lib/python3.6/dist-packages/wot/graphics/__init__.py", line 4, in <module>
    from .plot import *
  File "/usr/local/lib/python3.6/dist-packages/wot/graphics/plot.py", line 5, in <module>
    from matplotlib import pyplot as plt
  File "/usr/lib/python3/dist-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/lib/python3/dist-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  matplotlib.use("Agg")
Transforming to str index.
Traceback (most recent call last):
  File "/usr/local/bin/wot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/wot/__main__.py", line 23, in main
    cmd.main(args)
  File "/usr/local/lib/python3.6/dist-packages/wot/commands/trajectory_trends.py", line 32, in main
    results = wot.tmap.trajectory_trends_from_trajectory(trajectory_ds, matrix, day_field=cell_days_field)
  File "/usr/local/lib/python3.6/dist-packages/wot/tmap/util.py", line 148, in trajectory_trends_from_trajectory
    mean_ds = anndata.AnnData(mean_list[j], pd.DataFrame(index=timepoints), expression_ds.var.copy())
  File "/usr/local/lib/python3.6/dist-packages/anndata/core/anndata.py", line 570, in __init__
    filename=filename, filemode=filemode)
  File "/usr/local/lib/python3.6/dist-packages/anndata/core/anndata.py", line 762, in _init_as_actual
    ['obs_names', 'row_names', 'smp_names'])
  File "/usr/local/lib/python3.6/dist-packages/anndata/core/anndata.py", line 177, in _gen_dataframe
    anno.index = anno.index.astype(str)
  File "/usr/lib/python3/dist-packages/pandas/core/indexes/numeric.py", line 305, in astype
    self.__class__)
TypeError: Setting <class 'pandas.core.indexes.numeric.Float64Index'> dtype to anything other than float64 or object is not supported```

**Comment by joshua-gould** [comment]
An example for using pegasus to compute the FLE is at the bottom of
https://nbviewer.jupyter.org/github/broadinstitute/wot/blob/master/notebooks/Notebook-1-FLE-cell_sets-gene_sets.ipynb
.

trajectory_trends is supported. Can you please send me the command line and
data that generated the error? Thanks.

**Comment by mbk0asis** [comment]
Sorry for late reply.
I used the example data and command presented in the tutorial page.

Thank you!
