### ISSUE TITLE
error in wot.tmap.TransportMapModel.from_directory(TMAP_PATH)

### ISSUE THREAD

**Issue by rosshandler** [broadinstitute/wot#81]
Dear WOT team,

I have computed the transport maps as in the command line example. To do this, I generated an h5ad file using the convert matrix tool (from txt to hda5). Everything went fine. I just noticed that importing wot leads to the following warning:

FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex 

Then, when I want to use either the trajectory or fates tool (from command line or following the  notebook), I get the following error:

>> tmap_model = wot.tmap.TransportMapModel.from_directory(TMAP_PATH)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hps/research1/marioni/ivan/miniconda3/envs/embryo_wot/lib/python3.7/site-packages/wot/tmap/transport_map_model.py", line 716, in from_directory
    rids = f['/obs']['index'][()].astype(str)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/hps/research1/marioni/ivan/miniconda3/envs/embryo_wot/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'index' doesn't exist)"

I am using the latest version of wot (1.0.8).

Please let me know if you have any idea about what could be happening or if I should share more information.

Best,
Ivan

**Comment by joshua-gould** [comment]
Can you please make sure that only the transport maps are in the transport map directory (and not your input matrix)? Thanks.

**Comment by rosshandler** [comment]
Hi, 

Thanks a lot for such a quick answer. I already have them in separate folders. My command line is:
 wot fates --tmap tmaps/embryo  \
  --cell_set cellsets/cellsets.gmt --day 8.5 --out fates_mat/test --verbose

I generated another transport map in loom format and I get a very similar error:

home/iimaz/miniconda3/lib/python3.7/site-packages/anndata/_core/anndata.py:21: FutureWarning: pandas.core.index is deprecated and will be removed in a future version.  The public classes are available in the top-level namespace.
  from pandas.core.index import RangeIndex
Traceback (most recent call last):
  File "/home/iimaz/miniconda3/bin/wot", line 8, in <module>
    sys.exit(main())
  File "/home/iimaz/miniconda3/lib/python3.7/site-packages/wot/__main__.py", line 23, in main
    cmd.main(args)
  File "/home/iimaz/miniconda3/lib/python3.7/site-packages/wot/commands/fates.py", line 12, in main
    wot.commands.run_trajectory_or_fates(args, True)
  File "/home/iimaz/miniconda3/lib/python3.7/site-packages/wot/commands/util.py", line 43, in run_trajectory_or_fates
    tmap_model = wot.tmap.TransportMapModel.from_directory(args.tmap)
  File "/home/iimaz/miniconda3/lib/python3.7/site-packages/wot/tmap/transport_map_model.py", line 713, in from_directory
    rids = f['/row_attrs/id'][()].astype(str)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/iimaz/miniconda3/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'id' doesn't exist)"

**Comment by rosshandler** [comment]
Perhaps it is worth mentioning that I am running wot using a PCA matrix  (I used 'local_pca 0'). That too used to work in my previous experiences. I also checked all the file formats in the webpage and can't find any discrepancy. 

Thanks!

**Comment by MikeDMorgan** [comment]
I'm getting a similar issue: 
`  File "/nfs/research1/marioni/mdmorgan/miniconda3/envs/MDMorgan/bin/wot", line 8, in <module>
    sys.exit(main())
  File "/nfs/research1/marioni/mdmorgan/miniconda3/envs/MDMorgan/lib/python3.7/site-packages/wot/__main__.py", line 23, in main
    cmd.main(args)
  File "/nfs/research1/marioni/mdmorgan/miniconda3/envs/MDMorgan/lib/python3.7/site-packages/wot/commands/trajectory.py", line 12, in main
    wot.commands.run_trajectory_or_fates(args, False)
  File "/nfs/research1/marioni/mdmorgan/miniconda3/envs/MDMorgan/lib/python3.7/site-packages/wot/commands/util.py", line 43, in run_trajectory_or_fates
    tmap_model = wot.tmap.TransportMapModel.from_directory(args.tmap)
  File "/nfs/research1/marioni/mdmorgan/miniconda3/envs/MDMorgan/lib/python3.7/site-packages/wot/tmap/transport_map_model.py", line 716, in from_directory
    rids = f['/obs']['index'][()].astype(str)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/homes/mdmorgan/.local/lib/python3.7/site-packages/h5py/_hl/group.py", line 264, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'index' doesn't exist)"`

When trying to run the trajectory command-line tool thus:
`wot trajectory --tmap=wot_results/Lgr5DTR_only_tmaps --cell_set=data/Lgr5DTR_only_cellset.gmt --out=wot_results/Lgr5DTR_only_trajectory_day0  --day 0`

I can confirm that the transport maps and expression matrices are in separate directories.

This is with Pandas 0.25.2, h5py 2.10.0 and wot 1.0.8.

**Comment by joshua-gould** [comment]
What version of anndata are you using? I have 0.7.1 and haven't been able
to reproduce this error.

**Comment by rosshandler** [comment]
I have the same anndata version (0.7.1). I could share a transport map with you to see if you can read it.

**Comment by joshua-gould** [comment]
Can you please email several of your transport maps and an example cell set to reproduce your error to wot at broadinstitute.org? Thanks.

**Comment by rosshandler** [comment]
I just sent an email with the transport maps and an example cell set. Many thanks.

**Comment by joshua-gould** [comment]
Thanks, that was very helpful. I've identified the issue and should have a fix available shortly.

**Comment by joshua-gould** [comment]
Version 1.0.8.post1 has just been published which fixes this issue. Thanks.
